FROM alpine:3.2

MAINTAINER Hamdi LAADHARI @killerwolf

RUN apk --update add curl tar && \
	curl -L https://github.com/spf13/hugo/releases/download/v%%HUGO_VERSION%%/hugo_%%HUGO_VERSION%%_linux_amd64.tar.gz | tar xvz && \
	apk del curl tar && \
	mv /hugo_%%HUGO_VERSION%%_linux_amd64/hugo_%%HUGO_VERSION%%_linux_amd64 /bin/hugo  && \
	rm -fr /hugo_%%HUGO_VERSION%%_linux_amd64 && \
	rm -rf /var/cache/apk/*

EXPOSE 1313

ENTRYPOINT ["/bin/hugo"]
